on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

name: Outdated dependencies

jobs:
  outdated:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-outdated
          version: latest
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: outdated