on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

name: Unused dependencies

jobs:
  udeps:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-udeps
          version: latest
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --all-features --all-targets --color=always
